### ISSUE TITLE
error at first deploy if sentry is undefined

### ISSUE THREAD

**Issue by rafleze** [20tab/django-continuous-delivery#103]
```Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    main()
  File "manage.py", line 21, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/local/lib/python3.8/site-packages/configurations/importer.py", line 153, in load_module
    mod = imp.load_module(fullname, *self.location)
  File "/usr/local/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/local/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/pyroma20tab/settings.py", line 263, in <module>
    class Remote(ProjectDefault):
  File "/app/pyroma20tab/settings.py", line 276, in Remote
    sentry_sdk.init(integrations=[DjangoIntegration()], send_default_pii=True)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/hub.py", line 105, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/client.py", line 88, in __init__
    self._init_impl()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/client.py", line 119, in _init_impl
    self.transport = make_transport(self.options)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/transport.py", line 393, in make_transport
    return transport_cls(options)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/transport.py", line 127, in __init__
    Transport.__init__(self, options)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/transport.py", line 53, in __init__
    self.parsed_dsn = Dsn(options["dsn"])
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/utils.py", line 175, in __init__
    raise BadDsn("Unsupported scheme %r" % parts.scheme)
sentry_sdk.utils.BadDsn: Unsupported scheme ''```

**Comment by niccolomineo** [comment]
We recently transitioned to a new project boostrap where we took good care of this. I am closing this issue.
